#! /bin/sh -x

\rm FF_*
\rm ERRORS

# LLZO

/home/burbanom/bin/cp2k-gfortran-4.7.sopt input_LLZO01.inpt > cp2k_LLZO01.out
errors=$(grep 'Abnormal program termination' cp2k_LLZO01.out | wc -l)
echo $errors > ERRORS
if [ $errors -ne 0 ] ; then
  exit 1
fi
wc -l LLZO01-frc-1.xyz > xxx
read lines name < xxx
newlines=$((lines-2))
tail -$newlines LLZO01-frc-1.xyz | awk '{printf "%.7f %.7f %.7f\n",$2,$3,$4}' >> FF_FORCES
stress-bar-to-au.py LLZO01-1.stress
cat xxyyzzstress.out >>  FF_STRESSES
cat xyxzyzstress.out >> FF_STRESSES
head -$((lines-448)) LLZO01-DIPOLES-1_0.xyz >| dummy
tail -$((newlines-448)) dummy | awk '{printf "%.7f %.7f %.7f\n",$2,$3,$4}' >> FF_DIPOLES
\rm xxx dummy LLZO01-DIPOLES-1_0.xyz
